# Generated by Django 6.1.1 on 2026-09-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allow_spicy',
            field=models.BooleanField(default=False),
        ),
    ]
