# Generated by Django 6.1.1 on 2026-09-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_menuitem_allow_spicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allow_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='large_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
