# Generated by Django 6.1.1 on 2026-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_menuitem_allow_size_menuitem_large_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('service', 'Service'), ('food', 'Food'), ('speed', 'Speed'), ('atmosphere', 'Atmosphere')], max_length=20)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
