# Generated by Django 6.1.1 on 2026-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
