# Generated by Django 6.1.1 on 2026-09-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_feedback_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direct_print_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='direct_printed',
            field=models.BooleanField(default=False),
        ),
    ]
