# Generated by Django 6.1.1 on 2026-09-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0009_order_direct_print_sent_at_order_direct_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
